# config for clud build
steps:
  # Step 1: Build the Docker image with Maven and Firefox dependencies
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "a360-tests", "."]

  # Step 2: Run the tests inside the Docker container
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "--rm", "a360-tests", "mvn", "clean", "install"]

options:
  logging: CLOUD_LOGGING_ONLY
# config for clud run
# steps:
#   # Step 1: Build the Docker image with Maven and Firefox dependencies
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["build", "-t", "gcr.io/[PROJECT_ID]/a360-tests", "."]

#   # Step 2: Push the Docker image to Google Container Registry (GCR)
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "gcr.io/[PROJECT_ID]/a360-tests"]

# options:
#   logging: CLOUD_LOGGING_ONLY
