steps:
  # Step 1: Build the Docker image with Maven and Firefox dependencies
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "my-app-image", "."]

  # Step 2: Run the tests inside the Docker container
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "--rm", "my-app-image", "mvn", "clean", "install"]
