# steps:
#   # Build the Docker image
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["build", "-t", "gcr.io/aroma-gfunc/cucumber-tests", "."]

#   # Push the Docker image to Container Registry
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "gcr.io/aroma-gfunc/cucumber-tests"]

#   # Deploy the Docker image to Cloud Run
#   - name: "gcr.io/cloud-builders/gcloud"
#     args:
#       - "run"
#       - "deploy"
#       - "cucumber-tests"
#       - "--image"
#       - "gcr.io/aroma-gfunc/cucumber-tests"
#       - "--platform"
#       - "managed"
#       # Add other Cloud Run deployment options as needed
# options:
#   logging: CLOUD_LOGGING_ONLY

# steps:
#   # Build the Docker image
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       - "build"
#       - "-t"
#       - "gcr.io/aroma-gfunc/ar360-test"
#       - "."

#   # Push the Docker image to GCR
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       - "push"
#       - "gcr.io/aroma-gfunc/ar360-test"

# images:
#   - "gcr.io/aroma-gfunc/ar360-test"

# options:
#   logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Set up the environment
  - name: "gcr.io/cloud-builders/maven:3.8.4"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y firefox
        mvn --version

  # Step 2: Build and run tests
  - name: "gcr.io/cloud-builders/maven:3.8.4"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        export DISPLAY=:0
        mvn clean test -Dbrowser=firefox

# Timeout setting (optional)
timeout: "30m"
options:
  logging: CLOUD_LOGGING_ONLY
